### ISSUE TITLE
Too few control units error

### ISSUE THREAD

**Issue by mullachv** [laurencium/Causalinference#5]
Hi 
While using this package, I get raise ValueError('Too few control units: N_c < K+1')

I get the following error:
```
vs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
dfvs: (625, 22)
Traceback (most recent call last):
  File "/Users/vmullachery/mine/NYU/fall2018/probabilistic-gwas-playgound/framework/acic_init.py", line 107, in <module>
    init_data(args)
  File "/Users/vmullachery/mine/NYU/fall2018/probabilistic-gwas-playgound/framework/acic_init.py", line 84, in init_data
    cm(allf, list(allf.columns.difference(['A','Y']).values))
  File "/Users/vmullachery/mine/NYU/fall2018/probabilistic-gwas-playgound/framework/acic_init.py", line 24, in cm
    X=df[vs].values
  File "/Users/vmullachery/anaconda/envs/dl3.6/lib/python3.6/site-packages/causalinference/causal.py", line 17, in __init__
    self.old_data = Data(Y, D, X)
  File "/Users/vmullachery/anaconda/envs/dl3.6/lib/python3.6/site-packages/causalinference/core/data.py", line 63, in __init__
    raise ValueError('Too few control units: N_c < K+1')
ValueError: Too few control units: N_c < K+1

```

The code I am using:
```
print('vs:', vs)
print('dfvs:', df[vs].shape)
cm = CausalModel(
        Y=df.Y.values,
        D=df.A.values,
	X=df[vs].values
)		
# OLS
cm.est_via_ols(adj=1)

```

**Comment by mullachv** [comment]
Actually, I got this resolved. Just needed to carefully inspect the following:
- the number of treated
- the number of control
```
print(df[df.A==1].shape)
print(df[df.A==0].shape)
```

In my DataFrame there were zero controls
